### ISSUE TITLE
Krypton mod incompatibility

### ISSUE THREAD

**Issue by creeper123123321** [LilyPad/GoLilyPad#72] opened 2021-07-09 20:19 UTC
https://github.com/astei/krypton/issues/22#issuecomment-833287726

**Comment by coelho** [comment] 2021-07-09 20:27
@creeper123123321 

Please use the workaround provided by @astei
> You can work around it by adding -Dvelocity.natives-disabled=true to your Java startup flags.

We won't be fixing this bug as we only target compatibility with Vanilla.

**Closed by coelho** 2021-07-09 20:27 UTC

**Comment by magneticflux-** [comment] 2021-12-31 04:46
@coelho I believe this is caused by an upstream bug, and it can probably be fixed by simply updating klauspost/compress to 1.9 or 1.10 (or just to latest 😄). I believe since these commits it correctly writes the end-of-stream marker that `libdeflate` requires: https://github.com/klauspost/compress/commit/30993c63e1b02b47dd3878e74c8db50833706ecc or possibly https://github.com/klauspost/compress/commit/60e484491bdba55c5c152f12bd1262e5a1da790b
